runtime: custom
env: flex

#entrypoint: gunicorn -c gunicorn.conf.py -b :$PORT main:app --timeout 3600
entrypoint: gunicorn -c gunicorn.conf.py -b :$PORT main:app --timeout 600


runtime_config:
  python_version: 2


resources:
  cpu: 2 #scaled from 2
  memory_gb: 2 #scaled from 2
  disk_size_gb: 10 #scaled from 20

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.90

#health_check:
#  enable_health_check: false

liveness_check:
  path: "/health_check"
  check_interval_sec: 300
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/health_check"
  check_interval_sec: 300
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 1000

#referene
#https://cloud.google.com/appengine/docs/flexible/python/reference/app-yaml
